spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    password: ''
    url: jdbc:sqlite:../metadata/lookup.db
    username: ''
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl